micronaut:
  application:
    name: kdc

datasources:
  default:
    url: ${DB_URL:`jdbc:postgresql://localhost:5432/kdc`}
    driverClassName: org.postgresql.Driver
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:1234}

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
